application: decidable-plus
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
#- url: /icon-ux-blue\.png
#  static_files: templates/pictures/icon-ux-blue.png
#  upload: templates/pictures/icon-ux-blue\.png

- url: /decider_style\.css
  static_files: templates/decider_style.css
  upload: templates/decider_style\.css

- url: /chart\.js
  static_files: templates/chart.js
  upload: templates/chart\.js


- url: /(.*\.(png|jpg))
  static_files: templates/pictures/\1
  upload: templates/pictures/.*\.(png|jpg)


#- url: /blank_page\.jpg
#  static_files: templates/pictures/blank_page.jpg
#  upload: templates/pictures/blank_page\.jpg

#- url: /college_pic\.jpg
#  static_files: templates/pictures/college_pic.jpg
#  upload: templates/pictures/college_pic\.jpg

#- url: /house\.jpg
#  static_files: templates/pictures/house.jpg
#  upload: templates/pictures/house\.jpg

#- url: /download\.png
#  static_files: templates/pictures/download.png
#  upload: templates/pictures/download\.png

#- url: /junk-food\.jpg
#  static_files: templates/pictures/junk-food.jpg
#  upload: templates/pictures/junk-food\.jpg

- url: /chart\.js
  static_files: templates/chart.js
  upload: templates/chart\.js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
