application: decider
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /decider_style\.css
  static_files: templates/decider_style.css
  upload: templates/decider_style\.css

- url: /chart\.js
  static_files: templates/chart.js
  upload: templates/chart\.js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
